name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# permissions are needed if pushing to ghcr.io
permissions:
  packages: write

jobs:
  install:
    name: Test installation
    runs-on: ubuntu-latest-m

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Desktop
        id: start_desktop
        uses: asafchen-dig/desktop-action/start@main

      - name: Validate metadata
        run: docker extension validate ./metadata.json

      - name: Build extension
        run: docker build -t digma-docker-extension .

      # - name: Allow non-marketplace extensions
      #   run: |
      #     sudo mkdir -p /etc/docker 
      #     echo '{"settingsVersion": 30, "experimental": true, "extensions": {"allow-non-distributable-artifacts": true}}' | sudo tee /etc/docker/daemon.json 
      #     cat /etc/docker/daemon.json 
      #     sudo systemctl restart docker
      #     sleep 5
      #     journalctl -xeu docker.service

      - name: Install extension
        run: docker extension install digma-docker-extension -f

  build:
    name: Build
    needs: [install]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
