name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# permissions are needed if pushing to ghcr.io
permissions:
  packages: write

jobs:
  install:
    name: Test installation
    runs-on: ubuntu-latest-m

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Desktop
        id: start_desktop
        uses: docker/desktop-action/start@v0.3.6

      - name: Print Docker Desktop settings file before update
        shell: bash
        run: |
          SETTINGS_FILE="$HOME/.docker/desktop/settings.json"
          echo "Settings file before update:"
          if [ -f "$SETTINGS_FILE" ]; then
            cat "$SETTINGS_FILE"
          else
            echo "Settings file does not exist, it will be created."
          fi

      - name: Edit Docker Desktop setting file
        shell: bash
        run: |
          echo $(jq '. += {onlyMarketplaceExtensions: false}' ~/.docker/desktop/settings.json) > ~/.docker/desktop/settings.json
          echo ~/.docker/desktop/settings.json

      - name: Print Docker Desktop settings file after update
        shell: bash
        run: |
          SETTINGS_FILE="$HOME/.docker/desktop/settings.json"
          echo "Settings file after update:"
          if [ -f "$SETTINGS_FILE" ]; then
            cat "$SETTINGS_FILE"
          else
            echo "Settings file does not exist, it will be created."
          fi

      - name: Validate metadata
        run: docker extension validate ./metadata.json

      - name: Build extension
        run: docker build -t digma-docker-extension .

      - name: Install extension
        run: docker extension install digma-docker-extension -f

  build:
    name: Build
    needs: [install]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
