name: Publish release

# Controls when the workflow will run
on:
  pull_request:
# on:
#   workflow_dispatch:
#   release:
#     types: [released]

# permissions are needed if pushing to ghcr.io
permissions:
  packages: write

jobs:
  release:
    name: Build, validate and publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DIGMAAI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DIGMAAI_TOKEN }}

      # - name: Install Docker Extension plugin
      #   run: |
      #     docker plugin install extension

      # - name: Build and export to Docker
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     load: true
      #     tags: ${{ steps.metadata.outputs.tags }}

      # - name: Validate
      #   run: |
      #     docker extension validate digmaai/digma-docker-extension:${{ steps.metadata.outputs.tags }}

      - name: Docker meta
        id: metadata # you'll use this in the next step
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: digmaai/digma-docker-extension
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=v(.*),group=1
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            # set latest tag for main branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          # push: ${{ github.event_name != 'pull_request' }}
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
