name: Publish release

# Controls when the workflow will run
on:
  workflow_dispatch:
  release:
    types: [released]

# permissions are needed if pushing to ghcr.io
permissions:
  packages: write

jobs:
  install:
    name: Test the installation
    runs-on: ubuntu-latest-m

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Desktop
        id: start_desktop
        uses: docker/desktop-action/start@v0.3.6
        with:
          docker-desktop-build-url: "https://desktop.docker.com/linux/main/amd64/160616/docker-desktop-amd64.deb"

      - name: Print Docker Desktop settings file before update
        shell: bash
        run: |
          cat ~/.docker/desktop/settings.json

      - name: Edit Docker Desktop setting file
        shell: bash
        run: |
          jq '.onlyMarketplaceExtensions = false' ~/.docker/desktop/settings.json > tmp.$$.json && mv tmp.$$.json ~/.docker/desktop/settings.json

      - name: Print Docker Desktop settings file after update
        shell: bash
        run: |
          cat ~/.docker/desktop/settings.json
          
      - name: Restart Docker Daemon to Apply Settings
        shell: bash
        run: |
          sudo systemctl daemon-reload
          sudo systemctl restart docker
          
      - name: Verify settings after restart
        shell: bash
        run: |
          SETTINGS_FILE="$HOME/.docker/desktop/settings.json"
          cat "$SETTINGS_FILE" | grep '"onlyMarketplaceExtensions": false'
          if [ $? -eq 0 ]; then
            echo "Settings are correctly applied."
          else
            echo "Settings were not applied correctly."
            exit 1
          fi    
      
      - name: Verify settings change
        shell: bash
        run: |
          SETTINGS_FILE="$HOME/.docker/desktop/settings.json"
          if grep -q '"onlyMarketplaceExtensions": false' "$SETTINGS_FILE"; then
            echo "Settings are correct."
          else
            echo "Settings are NOT correct!"
            exit 1
          fi
          
      - name: Validate metadata
        run: docker extension validate ./metadata.json

      - name: Build extension
        run: docker build -t digma-docker-extension .

      - name: Install extension
        run: docker extension install digma-docker-extension -f

  build-and-push:
    name: Build and push to the DockerHub
    needs: [install]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DIGMAAI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DIGMAAI_TOKEN }}

      - name: Docker meta
        id: metadata # you'll use this in the next step
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: digmaai/digma-docker-extension
          # Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
